-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpjTW5bX4NqsJb7AS
ykiYeoL6zfdnOr2AF6ceopEODvmgCgYIKoZIzj0DAQehRANCAAT+5TRetmhByOmi
lr3BvRj4kmzH6e+AoMAxsI3yv6M+ivPxjr8S6L6tI4THdpSqVkuzcrOyNmJEokQq
t3mGtcXS
-----END PRIVATE KEY-----